# Generated by Django 3.0.8 on 2020-07-28 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='gallery')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('cakes', 'cakes'), ('cupcakes', 'cupcakes'), ('brownies', 'brownies'), ('macrons', 'macrons')], help_text='select category', max_length=20)),
                ('description', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID ', primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=30, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('delivery_date', models.DateTimeField(null=True)),
                ('ordered', models.BooleanField(default=False, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('location', models.CharField(choices=[('kasaragod', 'kasaragod'), ('kumbala', 'kumbala'), ('eriyal', 'eriyal'), ('chowki', 'chowki')], help_text='select location', max_length=20, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile_num', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('upi_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('size', models.PositiveIntegerField(default=1, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, null=True)),
                ('messages', models.CharField(blank=True, max_length=49, null=True)),
                ('instructions', models.CharField(blank=True, max_length=49, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Item')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Seller'),
        ),
    ]
