# Generated by Django 3.0.8 on 2020-07-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='messages',
            new_name='message',
        ),
    ]
