# Generated by Django 3.0.8 on 2020-08-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200809_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='default.jpg', null=True, upload_to='gallery'),
        ),
    ]
