# Generated by Django 3.0.8 on 2020-08-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200814_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_order_price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
